name: food_express
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <=3.0.5"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  font_awesome_flutter:
  fluttertoast:
  page_transition:
  flutter_spinkit:
  shared_preferences:
  provider:
  bubble_bottom_bar: ^2.0.0
  flutter_slidable: ^0.6.0
  google_maps_flutter:
  sliding_up_panel:
  flutter_polyline_points:
  dotted_border:
  intl_phone_number_input:
  platform: ^3.1.0
  file: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/category/
    - assets/products/
    - assets/restaurant/
    - assets/slider/
    - assets/user_profile/
    - assets/payment/
    - assets/onboarding/

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/roboto/Roboto-Regular.ttf
        - asset: fonts/roboto/Roboto-Light.ttf
          weight: 300
        - asset: fonts/roboto/Roboto-Medium.ttf
          weight: 500